### ISSUE TITLE
Module parse failed: Unexpected token.

### ISSUE THREAD

**Issue by duplich** [cezarlz/react-cl-audio-player#16]
FULL ERROR:
```
Module parse failed: Unexpected token.
You may need an appropriate loader to handle this file type.
```
I really like the plugin. But I tried to use it with create-react-app 
and it seems to have problem with webpack config. 
do we need custom config in order to use this?
Greetings

**Comment by vibhavjagwani** [comment]
I have the same error as Duplich! Any updates?

**Comment by duplich** [comment]
I was trying to fix it, but in the end I downloaded whole react-cl-audio-player repository and built my mini app on top of it. The dev version is to be seen on [Mini Music player App (Wp REST API & React)](http://songmonk.de/digital-ar-sync/)

**Comment by cezarlz** [comment]
Hey guys, thank you for your interest in this library. I've not been receiving notifications from GitHub, that's why I could not answer you.

I'll try to fix that this week. Thank you.

**Comment by cezarlz** [comment]
Another thing regarding that, I will update it to work with React 16.

**Comment by indatawetrust** [comment]
Do you have any regulations on this?

**Comment by cezarlz** [comment]
@indatawetrust not yet... I'll fix it today.

**Comment by cezarlz** [comment]
Hey devs I just sent the version 2.1.0 now, please check it out if it is working fine :)

**Comment by indatawetrust** [comment]
@cezarlz thank you so much. worked.
