### ISSUE TITLE
Gapping Loop

### ISSUE THREAD

**Issue by dennisotugo** [cezarlz/react-cl-audio-player#20]
Whenever I play a song on a loop there is a gap before the song start, is there any way to crossfade over that gap or to remove the gap itself

**Comment by cezarlz** [comment]
@dennisotugo nope... probably the gap is caused because the song wasn't loaded yet.

**Comment by dennisotugo** [comment]
Is there any way around that?

**Comment by cezarlz** [comment]
Using this library, not. It doesn't have a support for that :/
